extends: 
  - standard
  - prettier
  - prettier/standard
parser: ./lib/coffeescript/index.js
globals:
  ok: no
  eq: no
  test: no
  throws: no
  CoffeeScript: no
  arrayEq: no
  deepEqual: no
  doesNotThrow: no
