extends: 
  - standard
  - prettier
  - prettier/standard
parser: ./lib/coffeescript/index.js
globals:
  ok: no
  eq: no
  test: no
  throws: no
  CoffeeScript: no
  arrayEq: no
  deepEqual: no
  doesNotThrow: no
rules:
  no-new-object: error
  no-array-constructor: error
  object-shorthand: [error, properties]
  array-callback-return: error
  prefer-destructuring: error
  prefer-template: error
  no-useless-concat: error
  no-eval: error
  no-implied-eval: error
  func-style: error
  no-loop-func: error
  no-new-func: error
  no-param-reassign: [error, props: true]
  prefer-spread: error
  no-useless-constructor: error
  no-duplicate-imports: error
  import/prefer-default-export: error
  # import/first: [error, absolute-first]
  import/no-webpack-loader-syntax: error
  no-iterator: error
  no-restricted-syntax: [error, WithStatement]
  dot-notation: error
  no-restricted-properties: [error, {object: 'Math', property: 'pow'}]
  no-plusplus: [error, allowForLoopAfterthoughts: true]
  eqeqeq: [error, always, null: ignore]
  no-case-declarations: error
  no-unneeded-ternary: error
  no-new-wrappers: error
  radix: error
  camelcase: [error, properties: always]
  new-cap: [error, capIsNew: true]
  no-underscore-dangle: error
  no-restricted-globals: [error, location]
  constructor-super: error
  no-restricted-imports: [error, patterns: [lodash*]]
  no-useless-rename: error
  prefer-numeric-literals: error
  sort-imports: error
  for-direction: error
  getter-return: error
  no-await-in-loop: error
  no-console: error
  no-constant-condition: [error, checkLoops: true]
  no-empty: [error, allowEmptyCatch: true]
  no-empty-character-class: error
  no-prototype-builtins: error
  no-template-curly-in-string: warn
  one-var: off
  no-sequences: off
  valid-jsdoc: error
  accessor-pairs: error
  block-scoped-var: error
  class-methods-use-this: error
  consistent-return: error
  default-case: error
  guard-for-in: error
  no-alert: error
  no-caller: error
  no-div-regex: error

  yoda: off
